apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: broken-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nguyenthiyen356/http-api/'
    targetRevision: main
    path: troubleshoot
    directory:
      include: fixed-app.yaml
  destination:
    name: in-cluster
    namespace: troubleshoot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
