replicaCount: 3

image:
  repository: ghcr.io/nguyenthiyen356/http-api
  pullPolicy: IfNotPresent
  tag: "f808ca6" # Overridden dynamically by 20-deploy.sh

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

probes:
  liveness:
    path: /healthz
    port: 8080
    initialDelaySeconds: 15
    periodSeconds: 20
  readiness:
    path: /readyz
    port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: quote-api.local
      paths:
        - path: /
          pathType: Prefix

hpa:
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

pdb:
  minAvailable: 2

placement:
  nodeLabelKey: acme.io/capacity
  hostnameLabelKey: kubernetes.io/hostname
  spotValue: spot
  onDemandValue: on-demand
